### ISSUE TITLE
when rocko/sumo and debian stretch will be supported?

### ISSUE THREAD

**Issue by Ks89** [meta-debian/meta-debian#102]
Hi!

I'm interested in this package, but I need it for both rocko and sumo (next month).

When this package will be updated to support these versions?

PS: when debian stretch will be supported?

thank u.

**Comment by sangorrin** [comment]
meta-debian will support Debian buster in the next phase.
You can see the work-in-prograss here:
https://github.com/meta-debian/meta-debian/tree/master-ng

**Comment by zuka0828** [comment]
Hi @Ks89 
Please use `master` branch instead of `master-ng` which is an old name of `master` and will be removed soon.
