### ISSUE TITLE
ncurses eroror in ubuntu 16.04

### ISSUE THREAD

**Issue by vsivanagulu** [meta-debian/meta-debian#107]
I'm following yocto debian setup for meta-debian readme on jethro branch.
MACHINE=qemuarm 

> m/home/vik/siva/debian-yocto/build/tmp/sysroots/x86_64-linux/usr/include -D_GNU_SOURCE -O2 -pipe  --param max-inline-insns-single=1200 -fPIC -c /home/vik/siva/debian-yocto/build/tmp/work/x86_64-linux/ncurses-native/5.9+20140913-r1/git/ncurses/base/lib_hline.c -o ../obj_s/lib_hline.o
| In file included from /home/vik/siva/debian-yocto/build/tmp/work/x86_64-linux/ncurses-native/5.9+20140913-r1/git/ncurses/curses.priv.h:325:0,
|                  from ../ncurses/lib_gen.c:19:
| _6947.c:843:15: error: expected ')' before 'int'
| ../include/curses.h:1631:56: note: in definition of macro 'mouse_trafo'
|  #define mouse_trafo(y,x,to_screen) wmouse_trafo(stdscr,y,x,to_screen)

> 
any clues to solve.

**Comment by sangorrin** [comment]
Please use Debian Jessie, or a container with Jessie.
Check this: 
https://gitlab.com/cip-project/cip-core/deby/tree/master/poky/meta-cip-qemux86-64
