### ISSUE TITLE
[morty] postfix-native: Cannot link libpq

### ISSUE THREAD

**Issue by zuka0828** [meta-debian/meta-debian#274]
Build conditions: Same as #256

After the two fixes (bd702d75ad766ab78ce463a6f9653c0c73c4de99 and c2138a24f9e6615d101363dfecbb7300e39a7593), `do_compile()` still fails with the following error:

```
gcc -I. -I../../include -DDEBIAN -DMAX_DYNAMIC_MAPS -DHAS_PCRE     -DHAS_SQLITE -DMYORIGIN_FROM_FILE     -DHAS_CDB     -DHAS_MYSQL -I/home/deby/poky/build-world/tmp/sysroots/x86_64-linux/usr/include/mysql     -DHAS_SQLITE -I/home/deby/poky/build-world/tmp/sysroots/x86_64-linux/usr/include     -DHAS_SSL -I/home/deby/poky/build-world/tmp/sysroots/x86_64-linux/usr/include/openssl     -DUSE_TLS -I. -I../../include -DDEBIAN -DMAX_DYNAMIC_MAPS -DHAS_PCRE         -DHAS_SQLITE -DMYORIGIN_FROM_FILE         -DHAS_CDB         -DHAS_MYSQL -I/home/deby/poky/build-world/tmp/sysroots/x86_64-linux/usr/include/mysql         -DHAS_SQLITE -I/home/deby/poky/build-world/tmp/sysroots/x86_64-linux/usr/include         -DHAS_SSL -I/home/deby/poky/build-world/tmp/sysroots/x86_64-linux/usr/include/openssl         -DUSE_TLS -shared -Wl,-soname,dict_pgsql.so -o dict_pgsql.so dict_pgsql.o  -L/home/deby/poky/build-world/tmp/sysroots/x86_64-linux/usr/lib -lssl -lcrypto -lpthread -ldb -lnsl -lresolv -lpq -L. -lutil -lglobal
ERROR: oe_runmake failed
/usr/bin/ld: cannot find -lpq
collect2: error: ld returned 1 exit status
Makefile:164: recipe for target 'dict_pgsql.so' failed
make: *** [dict_pgsql.so] Error 1
```

Link commands of other targets than `dict_pgsql.so` like `dict_pcre.so` finishes successfully.
I could not find any wrong things in `postfix-native`. For example,

* The link command of `dict_pgsql.so` also includes the correct search path `$(SYSLIBS) = /home/deby/poky/build-world/tmp/sysroots/x86_64-linux/usr/lib`
* `postfix-native` already `DEPENDS` on `postgresql-native` which provides `libpq.so`

I think we need to correct the install path of `libpq.so` by `postgresql-native`, which is now

    tmp/sysroots/x86_64-linux/usr/lib/x86_64-linux-gnu/libpq.so

but it should be

    tmp/sysroots/x86_64-linux/usr/lib/libpq.so

**Comment by hieunv-tsdv** [comment]
Dear Hayashi-san,

In my opinion, the libpq.so is installed correct path (https://packages.debian.org/jessie/amd64/libpq-dev/filelist).
The postfix need to search the _libpq.so_ in both of _tmp/sysroots/x86_64-linux/usr/lib/_ and _tmp/sysroots/x86_64-linux/usr/lib/x86_64-linux-gnu/_

I create a PR to fix this issue #276
Please check it and let me know if you have any comment.

**Comment by zuka0828** [comment]
@hieunv-tsdv Thank you very much.

Let me confirm that the correct path of `libpq.so`.
I'm testing `bitbake world` (as I mentioned in #256) and found that the most libraries are installed in `tmp/sysroots/x86_64-linux/usr/lib/`.

```
.../tmp/sysroots/x86_64-linux$ find usr/lib/lib* | wc -l
634
.../tmp/sysroots/x86_64-linux$ find usr/lib/x86_64-linux-gnu/lib* | wc -l
18
```

I only found the following library files in `tmp/sysroots/x86_64-linux/usr/lib/x86_64-linux-gnu`.
All of them are installed by `postgresql-native`. [0]
That is why I guessed the install path of `libpq.so` (and relatives) for native sysroot is not correct.

```
.../tmp/sysroots/x86_64-linux/usr/lib/x86_64-linux-gnu $ ls lib*
libecpg.a
libecpg.so
libecpg.so.6
libecpg.so.6.6
libecpg_compat.a
libecpg_compat.so
libecpg_compat.so.3
libecpg_compat.so.3.6
libpgcommon.a
libpgport.a
libpgtypes.a
libpgtypes.so
libpgtypes.so.3
libpgtypes.so.3.5
libpq.a
libpq.so
libpq.so.5
libpq.so.5.7
```

[0] https://packages.debian.org/source/jessie/postgresql-9.4

Could you check again if we need to update `postfix-native` (or `postgresql-native`) ?

**Comment by hieunv-tsdv** [comment]
@zuka0828 san,

You are right! The _libdir_ in the _native_ and _nativesdk_ doesn't set to multiarch.
> libdir_native=/usr/lib

I will check and fix the postgresql recipe.

**Comment by hieunv-tsdv** [comment]
@zuka0828 san,

I created a pull request to fix postgresql-native recipe: https://github.com/meta-debian/meta-debian/pull/277

Please check and let me know if you have any comment.

Thanks,
Hieu

**Comment by zuka0828** [comment]
@hieunv-tsdv I confirmed that #277 corrects the install path of postgresql-native libraries then postfix-native can be built successfully after rebuilding postgresql-native.Thanks a lot!
