### ISSUE TITLE
logout?

### ISSUE THREAD

**Issue by jeremiah** [meta-debian/meta-debian#31]
How does one logout of the Qemu86 session once started? I see that Ctrl-D is trapped with a message that says; "Console sh exited with 0, respawning..."

This happens with exit and Ctrl-D. logout, shutdown, quit are not found.

**Comment by zuka0828** [comment]
The default init program of the current meta-debian calls only the root shell without login. This init is implemented as a tiny script (tiny-init), that sets up the minimal things needed for system boot. This means that the login prompt is not provided by init and halt/poweroff doesn't work.

Please see the following script (/init) for more details about tiny-init.
https://github.com/meta-debian/meta-debian/blob/jethro/recipes-core/tiny-init/files/init
exit and Ctrl-D works, but root shell is immediately called again from /init.
You can temporally login/logout by calling login command from the root shell.

We are planing to discard tiny-init and use busybox as the default init instead for providing more essential init functions such as halt/poweroff. We'd like to shift to busybox init by the middle of this month.
