### ISSUE TITLE
docker: won't git clone poky repository

### ISSUE THREAD

**Issue by jeanparpaillon** [meta-debian/meta-debian#311]
When building meta-debian container from `docker`, it stops after trying to git clone poky reposiutory:
```
Cloning into '/home/deby/poky'...
fatal: unable to access 'https://git.yoctoproject.org/poky/': server certificate verification failed. CAfile: none CRLfile: none
ERROR: Service 'work' failed to build : The command '/bin/sh -c git clone $POKY_GIT_URL $HOME/poky' returned a non-zero code: 128

```

**Comment by jeanparpaillon** [comment]
My bad, error does not come from wqrong URL.
May it be the proxy ?

Anyway, I get the following error when building container from `docker` directory:

```
Cloning into '/home/deby/poky'...
fatal: unable to access 'https://git.yoctoproject.org/poky/': server certificate verification failed. CAfile: none CRLfile: none
ERROR: Service 'work' failed to build : The command '/bin/sh -c git clone $POKY_GIT_URL $HOME/poky' returned a non-zero code: 128
```

**Comment by jeanparpaillon** [comment]
Adding `ca-certificates` package won't help

**Comment by zuka0828** [comment]
Hi @jeanparpaillon , which branch are you using? If you are using `Dockerfile` in "morty" branch, please update the docker image using the latest `Dockerfile` which enables Extended LTS repository. Older packages in the container cause the error you are facing.

Reference: https://gitlab.com/cip-project/cip-core/deby/-/issues/15

**Comment by zuka0828** [comment]
No update for around a month, so I'd like to close this issue.
Feel free to reopen if the issue has not been solved yet.
