### ISSUE TITLE
gcc - No such file or directory

### ISSUE THREAD

**Issue by naveen230** [meta-debian/meta-debian#79]
I use morty branches of meta-debian meta-openembedded and I'm getting this errors
Error log:
ERROR: libgcc-4.9.2-r0 do_unpack_extra: Function failed: do_unpack_extra (log file is located at /build/tmp/work/cortexa7hf-neon-vfpv4-deby-linux-gnueabi/libgcc/4.9.2-r0/temp/log.do_unpack_extra.3868)
ERROR: Logfile of failure stored in: /build/tmp/work/cortexa7hf-neon-vfpv4-deby-linux-gnueabi/libgcc/4.9.2-r0/temp/log.do_unpack_extra.3868
Log data follows:
| DEBUG: SITE files ['endian-little', 'bit-32', 'arm-common', 'arm-32', 'common-linux', 'common-glibc', 'arm-linux', 'arm-linux-gnueabi', 'common']
| DEBUG: Executing shell function do_unpack_extra
| cp: cannot stat ‘/build/tmp/work-shared/gcc-4.9.2-r0/git/debian’: No such file or directory
| WARNING: exit code 1 from a shell command.
| ERROR: Function failed: do_unpack_extra (log file is located at /build/tmp/work/cortexa7hf-neon-vfpv4-deby-linux-gnueabi/libgcc/4.9.2-r0/temp/log.do_unpack_extra.3868)
ERROR: Task (/poky/meta-debian/recipes-debian/gcc/libgcc_debian.bb:do_unpack_extra) failed with exit code '1'
ERROR: gcc-runtime-4.9.2-r0 do_unpack_extra: Function failed: do_unpack_extra (log file is located at /build/tmp/work/cortexa7hf-neon-vfpv4-deby-linux-gnueabi/gcc-runtime/4.9.2-r0/temp/log.do_unpack_extra.3869)
ERROR: Logfile of failure stored in: /build/tmp/work/cortexa7hf-neon-vfpv4-deby-linux-gnueabi/gcc-runtime/4.9.2-r0/temp/log.do_unpack_extra.3869
Log data follows:
| DEBUG: SITE files ['endian-little', 'bit-32', 'arm-common', 'arm-32', 'common-linux', 'common-glibc', 'arm-linux', 'arm-linux-gnueabi', 'common']
| DEBUG: Executing shell function do_unpack_extra
| cp: cannot stat ‘/build/tmp/work-shared/gcc-4.9.2-r0/git/debian’: No such file or directory
| WARNING: exit code 1 from a shell command.
| ERROR: Function failed: do_unpack_extra (log file is located at /build/tmp/work/cortexa7hf-neon-vfpv4-deby-linux-gnueabi/gcc-runtime/4.9.2-r0/temp/log.do_unpack_extra.3869)
ERROR: Task (/poky/meta-debian/recipes-debian/gcc/gcc-runtime_debian.bb:do_unpack_extra) failed with exit code '1'
ERROR: linux-base-gitAUTOINC+0466de39fe-r0 do_configure: /build/tmp/work/raspberrypi3-deby-linux-gnueabi/linux-base/gitAUTOINC+0466de39fe-r0/git/arch/arm/configs//linux/arch/arm/configs/bcmrpi_defconfig not found
ERROR: linux-base-gitAUTOINC+0466de39fe-r0 do_configure: Function failed: do_configure (log file is located at /build/tmp/work/raspberrypi3-deby-linux-gnueabi/linux-base/gitAUTOINC+0466de39fe-r0/temp/log.do_configure.3870)
ERROR: Logfile of failure stored in: /build/tmp/work/raspberrypi3-deby-linux-gnueabi/linux-base/gitAUTOINC+0466de39fe-r0/temp/log.do_configure.3870
ERROR: Task (/poky/meta-debian/recipes-kernel/linux/linux-base_git.bb:do_configure) failed with exit code '1'
NOTE: Tasks Summary: Attempted 1153 tasks of which 1150 didn't need to be rerun and 3 failed.

Summary: 3 tasks failed:
  /poky/meta-debian/recipes-debian/gcc/libgcc_debian.bb:do_unpack_extra
  /poky/meta-debian/recipes-debian/gcc/gcc-runtime_debian.bb:do_unpack_extra
  /poky/meta-debian/recipes-kernel/linux/linux-base_git.bb:do_configure

**Comment by sangorrin** [comment]
Probably this is fixed by now. I am sorry that nobody cared about your comment at the time.
Can you build this in your environment?
https://gitlab.com/cip-project/cip-core/deby/tree/master/poky/meta-cip-qemux86-64
