### ISSUE TITLE
gcc-runtime-4.9.2-r0 do_compile: oe_runmake failed

### ISSUE THREAD

**Issue by pavankumar-n-46** [meta-debian/meta-debian#92]
0
down vote
favorite

I followed the instruction provided by meta-debian github page: 
[](https://github.com/meta-debian/meta-debian)

During the build process I faced errors while bitbake was do-compiling some of the recipes.. they are **e2fsprogs, busybox, gettext** etc..

I searched the respective layers i.e, meta and meta-debian and found out that this recipes were present in both the layers.

I removed **e2fsprogs** from **meta** layer and **busybox, gettext** from **meta-debian** and bitbaked again, this removed the errors which was showing previously during bitbake. I did this because same recipes was present in the both the layers.

now the build is completed up to 90% but I'm stuck at gcc-runtime-4.9.2-r0 do_compile error.

I tried hard but I'm not able to solve this error.

**The entire terminal output is as shown below.**

pavan@work:/media/pavan/WD03/build$ bitbake core-image-minimal
WARNING: Host distribution "Ubuntu-16.04" has not been validated with this version of the build system; you may possibly experience unexpected failures. It is recommended that you use a tested distribution.
Loading cache: 100% |###########################################################################################################| Time: 0:00:01
Loaded 1449 entries from dependency cache.
Parsing recipes: 100% |#########################################################################################################| Time: 0:01:37
Parsing of 1624 .bb files complete (956 cached, 668 parsed). 2429 targets, 348 skipped, 0 masked, 0 errors.
NOTE: Resolving any missing task queue dependencies

Build Configuration:
BB_VERSION        = "1.32.0"
BUILD_SYS         = "x86_64-linux"
NATIVELSBSTRING   = "Ubuntu-16.04"
TARGET_SYS        = "i586-deby-linux"
MACHINE           = "qemux86"
DISTRO            = "deby"
DISTRO_VERSION    = "8.0"
TUNE_FEATURES     = "m32 i586"
TARGET_FPU        = ""
meta              = "morty:34b26ec18450a3bc72f7b8a0f2df0bfaae1140dd"
meta-debian       = "morty:ac8a24e0e42fbcdeb45fc586994503e2bc1f4196"

Initialising tasks: 100% |######################################################################################################| Time: 0:00:17
NOTE: Executing SetScene Tasks
NOTE: Executing RunQueue Tasks

**ERROR: gcc-runtime-4.9.2-r0 do_compile: oe_runmake failed**

**ERROR: gcc-runtime-4.9.2-r0 do_compile: Function failed: do_compile (log file is located at /media/pavan/WD03/build/tmp/work/i586-deby-linux/gcc-runtime/4.9.2-r0/temp/log.do_compile.18839)**

**ERROR: Logfile of failure stored in: /media/pavan/WD03/build/tmp/work/i586-deby-linux/gcc-runtime/4.9.2-r0/temp/log.do_compile.18839**

Log data follows: | DEBUG: SITE files ['endian-little', 'bit-32', 'ix86-common', 'common-linux', 'common-glibc', 'i586-linux', 'common'] | DEBUG: Executing shell function do_compile | NOTE: make -j 4 ARCH_FLAGS_FOR_TARGET= -m32 -march=i586 -isystem/media/pavan/WD03/build/tmp/sysroots/qemux86/usr/include MULTIBUILDTOP=/media/pavan/WD03/build/tmp/work/i586-deby-linux/gcc-runtime/4.9.2-r0/gcc-4.9.2/build.i586-deby-linux.i586-deby-linux/i586-deby-linux/libgcc/ | # If this is the top-level multilib, build all the other | DEFINES='' HEADERS='/media/pavan/WD03/build/tmp/work/i586-deby-linux/gcc-runtime/4.9.2-r0/git/src/libgcc/config/i386/value-unwind.h' \ | /media/pavan/WD03/build/tmp/work/i586-deby-linux/gcc-runtime/4.9.2-r0/git/src/libgcc/mkheader.sh > tmp-libgcc_tm.h | # multilibs. | /bin/bash /media/pavan/WD03/build/tmp/work/i586-deby-linux/gcc-runtime/4.9.2-r0/git/src/libgcc/../move-if-change tmp-libgcc_tm.h libgcc_tm.h | i586-deby-linux-gcc -m32 -march=i586 --sysroot=/media/pavan/WD03/build/tmp/sysroots/qemux86 -O2 -pipe -g -feliminate-unused-debug-types -fdebug-prefix-map=/media/pavan/WD03/build/tmp/work/i586-deby-linux/gcc-runtime/4.9.2-r0=/usr/src/debug/gcc-runtime/4.9.2-r0 -fdebug-prefix-map=/media/pavan/WD03/build/tmp/sysroots/x86_64-linux= -fdebug-prefix-map=/media/pavan/WD03/build/tmp/sysroots/qemux86= -O2 -g -Os -DIN_GCC -DCROSS_DIRECTORY_STRUCTURE -W -Wall -Wno-narrowing -Wwrite-strings -Wcast-qual -Wstrict-prototypes -Wmissing-prototypes -Wold-style-definition -isystem ./include -fpic -mlong-double-80 -g -DIN_LIBGCC2 -fbuilding-libgcc -fno-stack-protector -fpic -mlong-double-80 -I. -I. -I/media/pavan/WD03/build/tmp/work/i586-deby-linux/gcc-runtime/4.9.2-r0/gcc-4.9.2/build.i586-deby-linux.i586-deby-linux/i586-deby-linux/libgcc/../.././gcc -I/media/pavan/WD03/build/tmp/work/i586-deby-linux/gcc-runtime/4.9.2-r0/git/src/libgcc -I/media/pavan/WD03/build/tmp/work/i586-deby-linux/gcc-runtime/4.9.2-r0/git/src/libgcc/. -I/media/pavan/WD03/build/tmp/work/i586-deby-linux/gcc-runtime/4.9.2-r0/git/src/libgcc/../gcc -I/media/pavan/WD03/build/tmp/work/i586-deby-linux/gcc-runtime/4.9.2-r0/git/src/libgcc/../include -I/media/pavan/WD03/build/tmp/work/i586-deby-linux/gcc-runtime/4.9.2-r0/git/src/libgcc/config/libbid -DENABLE_DECIMAL_BID_FORMAT -DHAVE_CC_TLS -DUSE_TLS -o morestack_s.o -MT morestack_s.o -MD -MP -MF morestack_s.dep -DSHARED -c -xassembler-with-cpp /media/pavan/WD03/build/tmp/work/i586-deby-linux/gcc-runtime/4.9.2-r0/git/src/libgcc/config/i386/morestack.S | sed -e 's/PFX//g' \ | -e 's/__FIXPTPFX/__/g' < /media/pavan/WD03/build/tmp/work/i586-deby-linux/gcc-runtime/4.9.2-r0/git/src/libgcc/libgcc-std.ver.in > libgcc-std.ver PIC -DPIC -fno-implicit-templates -Wall -Wextra -Wwrite-strings -Wcast-qual -Wabi -fdiagnostics-show-location=once -ffunction-sections -fdata-sections -frandom-seed=compatibility-condvar.lo -O2 -pipe -g -feliminate-unused-debug-types -fdebug-prefix-map=/media/pavan/WD03/build/tmp/work/i586-deby-linux/gcc-runtime/4.9.2-r0=/usr/src/debug/gcc-runtime/4.9.2-r0 -fdebug-prefix-map=/media/pavan/WD03/build/tmp/sysroots/x86_64-linux= -fdebug-prefix-map=/media/pavan/WD03/build/tmp/sysroots/qemux86= -std=gnu++11 -c /media/pavan/WD03/build/tmp/work/i586-deby-linux/gcc-runtime/4.9.2-r0/git/src/libstdc++-v3/src/c++11/compatibility-condvar.cc -o compatibility-condvar.o >/dev/null 2>&1 | /bin/bash ../libtool --tag CXX --mode=link i586-deby-linux-g++ -m32 -march=i586 --sysroot=/media/pavan/WD03/build/tmp/sysroots/qemux86 -nostdinc++ -nostdlib++ -Wl,-O1 -Wl,-z,relro -Wl,--gc-sections -fPIC -DPIC -fno-implicit-templates -Wall -Wextra -Wwrite-strings -Wcast-qual -Wabi -fdiagnostics-show-location=once -ffunction-sections -fdata-sections -frandom-seed=libstdc++.la '-Wl,-O1' '-Wl,--hash-style=gnu' -o libstdc++.la -version-info 6:20:0 -Wl,--version-script=libstdc++-symbols.ver -lm -rpath /usr/lib compatibility.lo compatibility-debug_list.lo compatibility-debug_list-2.lo compatibility-c++0x.lo compatibility-atomic-c++0x.lo compatibility-thread-c++0x.lo compatibility-chrono.lo compatibility-condvar.lo ../libsupc++/libsupc++convenience.la ../src/c++98/libc++98convenience.la ../src/c++11/libc++11convenience.la | libtool: link: i586-deby-linux-g++ -m32 -march=i586 --sysroot=/media/pavan/WD03/build/tmp/sysroots/qemux86 -nostdinc++ -nostdlib++ -shared -nostdlib /media/pavan/WD03/build/tmp/sysroots/qemux86/usr/lib/crti.o /media/pavan/WD03/build/tmp/sysroots/qemux86/usr/lib/i586-deby-linux/4.9/crtbeginS.o .libs/compatibility.o .libs/compatibility-debug_list.o .libs/compatibility-debug_list-2.o .libs/compatibility-c++0x.o .libs/compatibility-atomic-c++0x.o .libs/compatibility-thread-c++0x.o .libs/compatibility-chrono.o .libs/compatibility-condvar.o -Wl,--whole-archive ../libsupc++/.libs/libsupc++convenience.a ../src/c++98/.libs/libc++98convenience.a ../src/c++11/.libs/libc++11convenience.a -Wl,--no-whole-archive -lm -L/media/pavan/WD03/build/tmp/sysroots/x86_64-linux/usr/lib/i586-deby-linux/gcc/i586-deby-linux/4.9 -L/media/pavan/WD03/build/tmp/sysroots/qemux86/lib -L/media/pavan/WD03/build/tmp/sysroots/qemux86/usr/lib/i586-deby-linux/4.9 -L/media/pavan/WD03/build/tmp/sysroots/qemux86/usr/lib -lc -lgcc_s /media/pavan/WD03/build/tmp/sysroots/qemux86/usr/lib/i586-deby-linux/4.9/crtendS.o /media/pavan/WD03/build/tmp/sysroots/qemux86/usr/lib/crtn.o -m32 -march=i586 -Wl,-O1 -Wl,-z -Wl,relro -Wl,--gc-sections -Wl,-O1 -Wl,--hash-style=gnu -Wl,--version-script=libstdc++-symbols.ver -Wl,-soname -Wl,libstdc++.so.6 -o .libs/libstdc++.so.6.0.20
 | ../src/c++11/.libs/libc++11convenience.a(system_error.o): In function __static_initialization_and_destruction_0':
| /usr/src/debug/gcc-runtime/4.9.2-r0/git/src/libstdc++-v3/src/c++11/system_error.cc:65: undefined reference to__dso_handle' 
| /media/pavan/WD03/build/tmp/sysroots/x86_64-linux/usr/libexec/i586-deby-linux/gcc/i586-deby-linux/4.9/ld: ../src/c++11/.libs/libc++11convenience.a(system_error.o): relocation R_386_GOTOFF against undefined hidden symbol `__dso_handle' can not be used when making a shared object 
| /media/pavan/WD03/build/tmp/sysroots/x86_64-linux/usr/libexec/i586-deby-linux/gcc/i586-deby-linux/4.9/ld: final link failed: Bad value 
| collect2: error: ld returned 1 exit status
 | Makefile:555: recipe for target 'libstdc++.la' failed | make[3]: * [libstdc++.la] Error 1 
| make[3]: Leaving directory '/media/pavan/WD03/build/tmp/work/i586-deby-linux/gcc-runtime/4.9.2-r0/gcc-4.9.2/build.i586-deby-linux.i586-deby-linux/i586-deby-linux/libstdc++-v3/src'
 | Makefile:585: recipe for target 'all-recursive' failed | make[2]: [all-recursive] Error 1
 | make[2]: Leaving directory '/media/pavan/WD03/build/tmp/work/i586-deby-linux/gcc-runtime/4.9.2-r0/gcc-4.9.2/build.i586-deby-linux.i586-deby-linux/i586-deby-linux/libstdc++-v3/src'
 | Makefile:485: recipe for target 'all-recursive' failed 
| make[1]: [all-recursive] Error 1 
| make[1]: Leaving directory '/media/pavan/WD03/build/tmp/work/i586-deby-linux/gcc-runtime/4.9.2-r0/gcc-4.9.2/build.i586-deby-linux.i586-deby-linux/i586-deby-linux/libstdc++-v3' 
| Makefile:391: recipe for target 'all' failed 
| make: * [all] Error 2 | ERROR: Function failed: do_compile (log file is located at /media/pavan/WD03/build/tmp/work/i586-deby-linux/gcc-runtime/4.9.2-r0/temp/log.do_compile.18839)

**ERROR: Task (/media/pavan/WD03/poky/meta-debian/recipes-debian/gcc/gcc-runtime_debian.bb:do_compile) failed with exit code '1'**

NOTE: Tasks Summary: Attempted 1086 tasks of which 1070 didn't need to be rerun and 1 failed.

Summary: 1 task failed: /media/pavan/WD03/poky/meta-debian/recipes-debian/gcc/gcc-runtime_debian.bb:do_compile Summary: There was 1 WARNING message shown. Summary: There were 2 ERROR messages shown, returning a non-zero exit code.

I'm not able to solve this error. Please help me understand what is the actual problem that is causing this error and what are the possible solutions..

thank you.

**Comment by sangorrin** [comment]
Hi, sorry for the delay. Could you build on Debian Jessie or a Debian jessie container instead of the unsupported Ubuntu? thanks.
